### ISSUE TITLE
Syntax improvement - main.js

### ISSUE THREAD

**Issue by NacimHarfouche** [nfmohit-wpmudev/deploy-netlifypress#3]
I think that those syntax improvement can be add.

**main.js :** 
_(begin of the script)_

`( function( $ ) {
    $( document ).ready( function() {`

to 

`( $ => {
    $(function() {`

Because here you have one param (therefore you dont need **()** ) and you don't use "**this**" in the first fonction thus you can use a arrow func.

Then next you have the shortcut of ready, like you can see in this documentation : https://learn.jquery.com/using-jquery-core/document-ready/

**Comment by nfmohit-wpmudev** [comment]
Hi there, @NacimHarfouche !
I hope you are doing well today!

Thank you very much for your suggestion here. I plan to rewrite the plugin using ES6 very soon (and some ReactJS), so I'll surely consider applying this then.

Thank you.

Regards,
Nahid

**Comment by NacimHarfouche** [comment]
Thx I’m fine and I hope you too.

Yeah react is a good choice, there are many features in ES6 that make writing code easier.

Why do you not use variable string or objet to stock your stuff, your code will be more readable.

Ex:
`let something = ``; `

**Comment by nfmohit-wpmudev** [comment]
Hi @NacimHarfouche !

Thank you for your suggestion. I didn't find it important to structure the JS in such a way as it uses simple jQuery and is readable as is. But I'll keep your suggestion in mind for my ES6 rewrite.

For the meantime, I'll close this issue.

Thank you for your feedback!

Regards,
Nahid
